
[package]
name = "raft-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[[bin]]
name = "raft-local"
path = "src/main.rs"

[dependencies]
raft-core.workspace = true
raft-adapters.workspace = true

[lints]
workspace = true